### ISSUE TITLE
Support passing identifying parameters for zaaktype & resultaattype

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/bptl#155]
Currently, the create zaak work unit requires the zaaktype URL to create the zaak. This has a couple of drawbacks:

- Whenever a new zaaktype becomes active, the process models need updating
- When migrating between environments with different URLs (different subdomain for example, but also possibly migrating between test/acc), process models need to be updated

A similar problem exists for the setting of the zaak result where the resultaattype URL must be specified in the process model.

We can change the work units to accept parameters that can be used to look up these values instead, using the Catalogi API.

For the zaaktype, this means that we can use the combination of `zaaktype.identificatie`, `catalogus.rsin` and `catalogus.domein`. For resultaattype, we should be able to use `resultaattype.omschrijving`.

**Tasks**

- [x] Adapt `CreateZaakTask` work unit
    - [x] Make the `zaaktype` variable optional
    - [x] Add support for the `zaaktypeIdentificatie`, `catalogusRSIN` and `catalogusDomein` variables. `catalogusRSIN` can default to the `organisatieRSIN` variable (so it's an optional variable).
    - [x] Either `zaaktype` (url) or (`zaaktypeIdentificatie` and `catalogusDomein`) are required. If all of them are provided, `zaaktype` is prioritised as it's the most explicit.
    - [x] Given the `catalogusRSIN` and `catalogusDomein`, look up the relevant catalogus in the API (see https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.1.0/src/openapi.yaml#operation/catalogus_list)
    - [x] Given the resolved catalogus and `zaaktypeIdentificatie`, resolve the zaaktype (using https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.1.0/src/openapi.yaml#operation/zaaktype_list)
    - [x] From the list of resolved zaaktypen, pick the version that matches the current date (use `zaaktype.beginGeldigheid` and `zaaktype.eindeGeldigheid` for this)
    - [x] Write tests.
- [x] Adapt the `CreateResultaatTask` and `CloseZaakTask` work units
    - [x] Optionally, the `omschrijving` variable is supported. If both `omschrijving` and `resultaattype` are specified, the latter wins as it is more specific
    - [x] If `omschrijving` is provided, retrieve the resultaattypen of the zaak.zaaktype (using https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.1.0/src/openapi.yaml#operation/resultaattype_list) and select the correct one based on `resultaattype.omschrijving`. For practical reasons, I think we can ignore the upper/lower case here (unless you would have multiple hits, then BPTL should throw an error).
    - [x] Write tests.
